<a href="https://colab.research.google.com/github/beruscoder/AI_fromscratch/blob/main/filter_paddingstride_pooling_sctrach.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
image = np.array([
    [1,2,3,0,1],
    [0,1,2,3,2],
    [3,0,1,2,1],
    [2,1,3,0,0],
    [1,2,0,1,2]
])

kernel = np.array([
    [0,1,0],
    [1,-4,1],
    [0,1,0]
])


In [8]:
def convolve(image ,kernel):
  image_h,image_w = np.shape(image)
  kernel_h, kernel_w = np.shape(kernel)
  output_h = image_h-kernel_h+1
  output_w = image_w-kernel_w+1
  output = np.zeros((output_h,output_w))

  for i in range(output_h):
    for j in range(output_w):
      region = image[i:i+kernel_h, j:j+kernel_w]
      output[i][j] = np.sum(region * kernel)

  return output


In [9]:
result = convolve(image, kernel)
print(result)

[[  0.   0.  -6.]
 [  6.   3.  -3.]
 [  3. -10.   6.]]


In [10]:
def pad_image(image, pad):
  return np.pad(image, pad, mode ='constant', constant_values=0)

In [11]:
def padding_stride(image,kernel,stride=1,padding=0):
  if padding>0:
    image = pad_image(image,padding)

    image_h,image_w = image.shape
    kernel_h, kernel_w = kernel.shape
    output_h = (image_h - kernel_h) // stride+1
    output_w = (image_w - kernel_w) // stride+1
    output = np.zeros((output_h,output_w))

    for i in range(0, output_h * stride,stride): #you can write image_h - kernel_h + 1
      for j in range(0, output_w*stride, stride):
        region = image[i:i+kernel_h, j:j+kernel_w]
        output[i//stride, j//stride] = np.sum(region * kernel)

    return output


In [12]:
paded_output = padding_stride(image,kernel,stride=1,padding=1)
print(paded_output)

[[ -2.  -3.  -8.   7.  -2.]
 [  5.   0.   0.  -6.  -3.]
 [-10.   6.   3.  -3.   0.]
 [ -3.   3. -10.   6.   3.]
 [  0.  -6.   6.  -2.  -7.]]


In [14]:
def max_pooling(image, pool_size, stride):
    output_h, output_w = paded_output.shape
    pool_h = (output_h - pool_size) // stride+1
    pool_w = (output_w - pool_size) // stride+1
    output2 = np.zeros((pool_h,pool_w))

    for i in range(0, pool_h * stride,stride): #you can write image_h - kernel_h + 1
      for j in range(0, pool_w*stride, stride):
        region = image[i:i+pool_size, j:j+pool_size]
        output2[i//stride, j//stride] = np.max(region)

    return output2

In [16]:
max_pooling(paded_output,2,1)

array([[5., 0., 7., 7.],
       [6., 6., 3., 0.],
       [6., 6., 6., 6.],
       [3., 6., 6., 6.]])